### ISSUE TITLE
Design cleanup: Sign up

### ISSUE THREAD

**Issue by andrewmaier** [18F/micropurchase#1192] opened 2016-09-08 18:49 UTC
- For framing, see [the "sign up" vignette](https://docs.google.com/document/d/1lWPYtQLdyZ42ENPIMxITcAuALXr2ADswu0XUCB7hYb4/edit#heading=h.d5gogjx2hqfu)
- Styles and copy should match: https://pages.18f.gov/micropurchase/sign-up/
- **Docs** link should work.

Those ordered list styles, for reference
```
.layout-sign-up main .wrapper ol{
    padding: 0;
    margin: 0 auto 2em;    
    counter-reset: step;
}

.layout-sign-up main .wrapper ol li{
    list-style-type: none;
    counter-increment: step;
    max-width: 20em;
    margin: 0 auto;
    position: relative;
}

.layout-sign-up main .wrapper ol li::before{
    content: counter(step);
    border: 2px solid #fff;
    width: 1.8em;
    line-height: 1.6em;
    height: 1.8em;
    font-size: 20px;
    display: inline-block;
    vertical-align: middle;
    border-radius: 100%;
    background: #99005c;
    color: white;
    margin-bottom: -0.67em;
    z-index: 2;
    position: relative;
}

.layout-sign-up main .wrapper ol li::after{
    content: "";
    position: absolute;
    border-bottom: 3px double #7fdefe;
    left: 40%;
    right: 40%;
    top: 0.95em;
    z-index: 1;
}
```

**Comment by mtorres253** [comment] 2016-09-21 23:13
dupe of #1160

**Closed** 2016-09-21 23:13 UTC
Labels: Front-end
