### ISSUE TITLE
C2 URL not appearing on auction show page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1025] opened 2016-08-09 16:31 UTC
To duplicate

Go to https://micropurchase.18f.gov/admin/auctions/31

Expected behavior:
C2 URL appears in the C2 Proposal URL section of the page (in the gray box)
And the messaging in the status box contains a link to the C2 URL

Actual behavior: 
C2 URL does not appear in the C2 Proposal URL box, and the messaging in the status box does contain a link to the C2 URL

**Comment by jessieay** [comment] 2016-08-09 17:31
@mtorres253 looking at cap channel on Slack, it appears they had some outages yesterday. we should probably handle that better. in meantime, will re-fire request

**Comment by jessieay** [comment] 2016-08-09 17:42
error in Micropurchase: 
> Error message
CreateC2Proposal::Error: the server responded with status 422

error on C2's side:

> Error message
ActiveRecord::RecordNotSaved: Failed to replace steps because one or more of the new records could not be saved.

**Comment by jessieay** [comment] 2016-08-09 17:51
several proposals were created, but approval setup failed:

https://cap.18f.gov/admin/proposals/5082
https://cap.18f.gov/admin/proposals/5083
https://cap.18f.gov/admin/proposals/5084
https://cap.18f.gov/admin/proposals/5085
https://cap.18f.gov/admin/proposals/5086
https://cap.18f.gov/admin/proposals/5088
https://cap.18f.gov/admin/proposals/5093

it wasnt that requests were failing, but steps werent working. think this is related to micropurchase type


https://cap.18f.gov/proposals/5099
https://cap.18f.gov/proposals/5101
https://cap.18f.gov/proposals/5102

**Comment by jessieay** [comment] 2016-08-09 18:00
I know what the problem is. Alan is the requester and the purchaser, C2 has a validation on steps `user_is_not_requester`

**Comment by jessieay** [comment] 2016-08-09 18:03
https://github.com/18F/C2/pull/1448

**Comment by jessieay** [comment] 2016-08-09 22:00
Fixed. C2 request here: https://cap.18f.gov/proposals/5110

closing

**Closed by jessieay** 2016-08-09 22:00 UTC
Labels: bug, in progress
