### ISSUE TITLE
Winners page shows average time for vendors to get paid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#565] opened 2016-05-16 03:39 UTC
As a potential agency customer, I would be delighted to see how quickly the micropurchase team has been paying vendors, so the system should show me this. And our hypothesis is that this will create excitement with the agency customer, and get us more auctions

Scenario: Winners page shows average time for vendors to get paid
Given I am viewing the winner's page https://micropurchase.18f.gov/auctions/winners
And there are auctions that have been successfully delivered 
And the vendors for those auctions have been paid
Then I should see a section labeled "Average Award Payment Time"
And in that section, I should see the average payment time to vendors in days, from the delivery date of an auction

**Comment by jessieay** [comment] 2016-07-07 21:13
this is a dupe of https://github.com/18F/micropurchase/issues/705 -- closing

**Closed by jessieay** 2016-07-07 21:13 UTC
Labels: user story
