### ISSUE TITLE
Admin messsaging - Auction show page - Payment needed using "other" p-card

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1198] opened 2016-09-08 22:39 UTC
Given I am an admin managing auctions, if an auction has been accepted, and payment needs to happen on another p-card (partner agency's p-card for example), I should see the messaging reflecting that status in on the auction show page

- [x] **Scenario: Admin sees that accepted auction requires payment via other p-card (not 18F)**
- Given I am an authenticated admin
- And there is an auction using an other p-card (other p-card payment method) 
- And the auction has been accepted
- And there is a payment URL for the winning vendor on file
- When I navigate to the show page for that auction
- Then I should see the following message in the status box

> Pending payment from customer
> [auction.customer] has been asked to remit payment. You must manually mark this auction as paid when it is paid by the customer.

- And I should see a button labeled "Mark as paid"

<img width="345" alt="screen shot 2016-09-19 at 1 30 17 pm" src="https://cloud.githubusercontent.com/assets/100149/18647948/4524df24-7e6d-11e6-9850-98c78c48a0f2.png">

- [ ] **Scenario: Admin marks an auction as paid on the auction page**
- When I click on the Mark as Paid button
- Then the auction should be marked as paid

**Comment by harrisj** [comment] 2016-09-22 15:40
When the auction is marked as paid, should we set the c2_status to `:payment_confirmed` even though this is outside of C2 otherwise?

**Comment by mtorres253** [comment] 2016-09-22 15:45
I think that status is set by the vendor. After the auction is marked as paid, the vendor gets an email asking them to confirm payment, which they do via the UI (even for other p-cards). If that's not the case, I'll have to write another story for that (which is fine since we're cleaning this up)

**Comment by harrisj** [comment] 2016-09-23 15:48
So, I think I need to clarify what happens for the second feature here. We are outside the normal C2 status hierarchy because these are purchases not using our P-cards. It seems like we might need to add a few things

1. Should we have a `c2_not_applicable` state for these types of auctions? Otherwise we might need to make sure we check `purchase_card` field in cases where we key off `c2_status` (I _think_ we're okay for now, but...)
2. I need some clarity on what happens when the admin clicks "Mark as paid." It seems like right now that it should set `paid_at` to `Time.now` for the auction, and it sounds like it should also send an email to the vendor like the C2 `CheckPayment` action does.
3. Do we need to send an email to the customer as well? If so, that should spelled out in a different story.
4. I need some text for what the status box should be after mark_paid is clicked. This will be shown in situations where auction is accepted and pcard is other and paid_at is not nil.

**Closed** 2016-09-28 20:55 UTC
Labels: needs review, user story, workflow/messaging
