### ISSUE TITLE
System validates DUNS number length

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#436] opened 2016-04-19 18:49 UTC
As a registered vendor, I want to know whether the DUNS number I've entered for my profile is not formatted correctly, so that I can correct it before it gets saved to my profile, so the system should check to see if it is correctly formatted

Scenario: System checks for valid DUNS number length
Given that I am a vendor
And I have entered a value into the DUNS number field on my profile page
And my DUNS number is not 8, 9 or 13 digits long
When I click the "Save" button
Then I should see that the DUNS number I've entered is invalid
And I should see this message "The DUNS number you've entered is invalid: It should be a number that is 8, 9 or 13 digits in length. Please verify your DUNS number and try again."

Note: We should talk about whether it is really necessary, given that we are already checking with Sam.gov to see if the DUNS number exists.

**Comment by jessieay** [comment] 2016-04-22 16:35
this seems like a dupe of https://github.com/18F/micropurchase/issues/425 ? @mtorres253

**Comment by jessieay** [comment] 2016-04-22 17:38
closed via https://github.com/18F/micropurchase/pull/445

**Closed by jessieay** 2016-04-22 17:38 UTC
Labels: user story
